---
# This playbook deploys a simple kubeadm install.
- name: Bootstrap Tasks
  hosts:
    - master
    - worker
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: false
  roles:
    - common

- name: Install Kubernetes master
  hosts: master
  remote_user: "{{ ansible_remote_user }}"
  become: true
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - master
  #  - contiv
    - calico
    - helm

- name: Install nodes
  remote_user: "{{ ansible_remote_user }}"
  hosts: worker
  become: true
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - worker

# - import_playbook: deploy_contiv_network_config.yml
- import_playbook: deploy_istio.yml
# - import_playbook: deploy_sample_apps.yml
