---
- name: Get istio latest release version
  ansible.builtin.shell: 'curl -L -s https://api.github.com/repos/istio/istio/releases/latest | grep tag_name | sed "s/ *\"tag_name\": *\"\(.*\)\",*/\1/"'
  register: istio_ver
    
- name: Get istio's latest release
  ansible.builtin.shell: 'curl -L https://istio.io/downloadIstio | sh -'
  args:
    chdir: /tmp
   
- name: Copy istioctl to /usr/bin
  ansible.builtin.copy:
    src: /tmp/istio-{{ istio_ver.stdout }}/bin/istioctl
    dest: /usr/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Install base Istio
  ansible.builtin.command: "istioctl install --set profile=demo -y"
  args:
    chdir: /tmp/istio-{{ istio_ver.stdout }}/

- name: Label namespace to automatically inject Envoy sidecar proxies
  ansible.builtin.command: "kubectl label namespace default istio-injection=enabled"

- ansible.builtin.pause:
    minutes: 1
    prompt: "Make sure istio pods are started"

- name: Install Bookinfo Sample App
  ansible.builtin.command: "kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml"
  args:
    chdir: /tmp/istio-{{ istio_ver.stdout }}/
  when: deploy_sample_apps
  
- name: Associate Bookinfo Sample App with the Istio gateway
  ansible.builtin.command: "kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml"
  args:
    chdir: /tmp/istio-{{ istio_ver.stdout }}/
  when: deploy_sample_apps

- name: Ensure that there are no issues with the configuration
  ansible.builtin.command: "istioctl analyze"
  args:
    chdir: /tmp/istio-{{ istio_ver.stdout }}/
  when: deploy_sample_apps

- name: Location of Sample Files
  ansible.builtin.debug:
    msg: "The sample files are located at /tmp/istio-{{ istio_ver.stdout }}/samples/bookinfo/platform/kube/"